"""Database module."""
from app.database.connection import get_db, engine, Base, SessionLocal
from app.database.models import (
    User,
    Company,
    Customer,
    Product,
    Invoice,
    InvoiceItem,
    Payment,
    BankAccount,
    Account,
    Transaction,
    TransactionEntry,
    # Multi-currency
    Currency,
    ExchangeRate,
    ForexGainLoss,
    # Cost centers
    CostCenter,
    CostCategory,
    BudgetMaster,
    BudgetLine,
    # Inventory enhancements
    ProductUnit,
    PriceLevel,
    ProductPrice,
    SerialNumber,
    StockAdjustment,
    StockAdjustmentItem,
    DiscountRule,
    ManufacturingOrder,
    ManufacturingConsumption,
    ManufacturingByproduct,
    # Banking
    ChequeBook,
    Cheque,
    PostDatedCheque,
    BankReconciliation,
    ReconciliationEntry,
    RecurringTransaction,
    # Accounting
    BillAllocation,
    PeriodLock,
    AuditLog,
    NarrationTemplate,
    Scenario,
    # Account Mapping Templates
    AccountMapping,
    AccountMappingType,
    PayrollAccountConfig,
    # Miscellaneous
    Attachment,
    Notification,
    DashboardWidget,
    ExportLog,
    # Quotations
    Quotation,
    QuotationItem,
    QuotationStatus,
    # Delivery Challans
    DeliveryChallan,
    DeliveryChallanItem,
    DeliveryChallanType,
    DeliveryChallanStatus,
    # Sales Pipeline
    Contact,
    Enquiry,
    EnquirySource,
    EnquiryStatus,
    SalesTicket,
    SalesTicketStatus,
    SalesTicketStage,
    SalesTicketLog,
    SalesTicketLogAction,
    # Alternative Products
    AlternativeProduct,
    ProductAlternativeMapping,
)
from app.database.payroll_models import (
    Department,
    Designation,
    Employee,
    SalaryComponent,
    EmployeeSalaryStructure,
    PayrollRun,
    PayrollEntry,
    EmployeeLoan,
    LoanRepayment,
    EmployeeTaxDeclaration,
    ProfessionalTaxSlab,
    PayrollSettings,
    # Attendance and Leave
    Attendance,
    LeaveType,
    LeaveBalance,
    LeaveApplication,
    OvertimeRule,
    Holiday,
)
from app.database.bank_statement_models import (
    BankStatementEntry,
    BankStatementEntryStatus,
    MonthlyBankReconciliation,
)

__all__ = [
    "get_db",
    "engine",
    "Base",
    "SessionLocal",
    "User",
    "Company",
    "Customer",
    "Product",
    "Invoice",
    "InvoiceItem",
    "Payment",
    "BankAccount",
    "Account",
    "Transaction",
    "TransactionEntry",
    # Multi-currency
    "Currency",
    "ExchangeRate",
    "ForexGainLoss",
    # Cost centers
    "CostCenter",
    "CostCategory",
    "BudgetMaster",
    "BudgetLine",
    # Inventory enhancements
    "ProductUnit",
    "PriceLevel",
    "ProductPrice",
    "SerialNumber",
    "StockAdjustment",
    "StockAdjustmentItem",
    "DiscountRule",
    "ManufacturingOrder",
    "ManufacturingConsumption",
    "ManufacturingByproduct",
    # Banking
    "ChequeBook",
    "Cheque",
    "PostDatedCheque",
    "BankReconciliation",
    "ReconciliationEntry",
    "RecurringTransaction",
    # Accounting
    "BillAllocation",
    "PeriodLock",
    "AuditLog",
    "NarrationTemplate",
    "Scenario",
    # Account Mapping Templates
    "AccountMapping",
    "AccountMappingType",
    "PayrollAccountConfig",
    # Miscellaneous
    "Attachment",
    "Notification",
    "DashboardWidget",
    "ExportLog",
    # Quotations
    "Quotation",
    "QuotationItem",
    "QuotationStatus",
    # Delivery Challans
    "DeliveryChallan",
    "DeliveryChallanItem",
    "DeliveryChallanType",
    "DeliveryChallanStatus",
    # Sales Pipeline
    "Contact",
    "Enquiry",
    "EnquirySource",
    "EnquiryStatus",
    "SalesTicket",
    "SalesTicketStatus",
    "SalesTicketStage",
    "SalesTicketLog",
    "SalesTicketLogAction",
    # Alternative Products
    "AlternativeProduct",
    "ProductAlternativeMapping",
    # Payroll models
    "Department",
    "Designation",
    "Employee",
    "SalaryComponent",
    "EmployeeSalaryStructure",
    "PayrollRun",
    "PayrollEntry",
    "EmployeeLoan",
    "LoanRepayment",
    "EmployeeTaxDeclaration",
    "ProfessionalTaxSlab",
    "PayrollSettings",
    # Attendance and Leave
    "Attendance",
    "LeaveType",
    "LeaveBalance",
    "LeaveApplication",
    "OvertimeRule",
    "Holiday",
    # Bank Statement models
    "BankStatementEntry",
    "BankStatementEntryStatus",
    "MonthlyBankReconciliation",
]
